### ISSUE TITLE
Dependency over Android support

### ISSUE THREAD

**Issue by lucas34** [HotBitmapGG/RingProgressBar#5]
Hi,

Is the dependency over Android App compat is mandatory for the library ? Because i cannot see that you are using it from the code.

Lucas.

**Comment by HotBitmapGG** [comment]
Hello, is not mandatory，written using the Demo, the Android create project studio automatically add these libraries. @lucas34

**Comment by Jawnnypoo** [comment]
This has been fixed in https://github.com/HotBitmapGG/RingProgressBar/pull/8

**Comment by Jawnnypoo** [comment]
@HotBitmapGG Can you tag another release for this lib so that it is built on jitpack?

**Comment by HotBitmapGG** [comment]
@Jawnnypoo The code has been updated to jitpack v1.2.3.

**Comment by Jawnnypoo** [comment]
Nice, thanks! This issue can be closed then 😁
